# bare minimal
name: googlesheet

on:
    push:
      branches:
        - main

jobs:
    fetch:
      runs-on: ubuntu-latest
      steps:
        - id: jp_sheet
          uses: chronoscore622/sheets@main
          with:
            spreadsheetId: ${{ secrets.SHEET_ID }}
            key: ${{ secrets.SHEETS_API }}
            sheetName: 'Basic&Music'
        - id: echo
          uses: actions/github-script@v9.0.0
          with:
            github-token: ${{secrets.GITHUB_TOKEN}}
            script: |
                console.log(${{steps.jp_sheet.outputs.result}})
        - name: test
          run: |
            cat $HOME/data.json
