name: googlesheet

on:
    push:
      branches:
        - sheet_pull

jobs:
    fetch:
      runs-on: ubuntu-latest
      steps:
        - id: fetch_jp_sheet
          uses: chronoscore622/sheets@v0.0.5
          with:
            spreadsheetId: ${{ secrets.SHEET_ID }}
            key: ${{ secrets.SHEETS_API }}
            sheetName: 'Basic&Music'
        - id: echo
          run: echo ${{ steps.fetch_jp_sheet.outputs.result }}
        - id: parse
          uses: chronoscore622/sheets@v1.0.2
          with:
            data: ${{ steps.fetch_jp_sheet.outputs.result }}

